/**
 * BaSyx Asset Administration Shell HTTP REST-API
 * The full description of the generic BaSyx Asset Administration Shell HTTP REST-API
 *
 * OpenAPI spec version: v1
 * Contact: constantin.ziesche@bosch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OperationVariable } from './operationVariable';

export interface InvocationRequest { 
    requestId?: string;
    inputArguments?: Array<OperationVariable>;
    inoutputArguments?: Array<OperationVariable>;
    timeout?: number;
}