/**
 * BaSyx Asset Administration Shell HTTP REST-API
 * The full description of the generic BaSyx Asset Administration Shell HTTP REST-API
 *
 * OpenAPI spec version: v1
 * Contact: constantin.ziesche@bosch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type KeyElements = 'Undefined' | 'GlobalReference' | 'FragmentReference' | 'AccessPermissionRule' | 'AnnotatedRelationshipElement' | 'BasicEvent' | 'Blob' | 'Capability' | 'ConceptDictionary' | 'DataElement' | 'File' | 'Entity' | 'Event' | 'MultiLanguageProperty' | 'Operation' | 'Property' | 'Range' | 'ReferenceElement' | 'RelationshipElement' | 'SubmodelElement' | 'SubmodelElementCollection' | 'View' | 'Asset' | 'AssetAdministrationShell' | 'ConceptDescription' | 'Submodel';

export const KeyElements = {
    Undefined: 'Undefined' as KeyElements,
    GlobalReference: 'GlobalReference' as KeyElements,
    FragmentReference: 'FragmentReference' as KeyElements,
    AccessPermissionRule: 'AccessPermissionRule' as KeyElements,
    AnnotatedRelationshipElement: 'AnnotatedRelationshipElement' as KeyElements,
    BasicEvent: 'BasicEvent' as KeyElements,
    Blob: 'Blob' as KeyElements,
    Capability: 'Capability' as KeyElements,
    ConceptDictionary: 'ConceptDictionary' as KeyElements,
    DataElement: 'DataElement' as KeyElements,
    File: 'File' as KeyElements,
    Entity: 'Entity' as KeyElements,
    Event: 'Event' as KeyElements,
    MultiLanguageProperty: 'MultiLanguageProperty' as KeyElements,
    Operation: 'Operation' as KeyElements,
    Property: 'Property' as KeyElements,
    Range: 'Range' as KeyElements,
    ReferenceElement: 'ReferenceElement' as KeyElements,
    RelationshipElement: 'RelationshipElement' as KeyElements,
    SubmodelElement: 'SubmodelElement' as KeyElements,
    SubmodelElementCollection: 'SubmodelElementCollection' as KeyElements,
    View: 'View' as KeyElements,
    Asset: 'Asset' as KeyElements,
    AssetAdministrationShell: 'AssetAdministrationShell' as KeyElements,
    ConceptDescription: 'ConceptDescription' as KeyElements,
    Submodel: 'Submodel' as KeyElements
};