/**
 * BaSyx Asset Administration Shell HTTP REST-API
 * The full description of the generic BaSyx Asset Administration Shell HTTP REST-API
 *
 * OpenAPI spec version: v1
 * Contact: constantin.ziesche@bosch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type KeyType = 'Undefined' | 'Custom' | 'IRI' | 'URI' | 'IRDI' | 'IdShort' | 'FragmentId';

export const KeyType = {
    Undefined: 'Undefined' as KeyType,
    Custom: 'Custom' as KeyType,
    IRI: 'IRI' as KeyType,
    URI: 'URI' as KeyType,
    IRDI: 'IRDI' as KeyType,
    IdShort: 'IdShort' as KeyType,
    FragmentId: 'FragmentId' as KeyType
};