/**
 * BaSyx Asset Administration Shell HTTP REST-API
 * The full description of the generic BaSyx Asset Administration Shell HTTP REST-API
 *
 * OpenAPI spec version: v1
 * Contact: constantin.ziesche@bosch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type MessageType = 'Unspecified' | 'Debug' | 'Information' | 'Warning' | 'Error' | 'Fatal' | 'Exception';

export const MessageType = {
    Unspecified: 'Unspecified' as MessageType,
    Debug: 'Debug' as MessageType,
    Information: 'Information' as MessageType,
    Warning: 'Warning' as MessageType,
    Error: 'Error' as MessageType,
    Fatal: 'Fatal' as MessageType,
    Exception: 'Exception' as MessageType
};