/**
 * BaSyx Asset Administration Shell HTTP REST-API
 * The full description of the generic BaSyx Asset Administration Shell HTTP REST-API
 *
 * OpenAPI spec version: v1
 * Contact: constantin.ziesche@bosch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LangString } from './langString';
import { ModelType } from './modelType';
import { Reference } from './reference';

export interface View { 
    idShort?: string;
    containedElements?: Array<Reference>;
    semanticId?: Reference;
    category?: string;
    description?: Array<LangString>;
    modelType?: ModelType;
}